import {
  BookOpen,
  Boxes,
  Braces,
  Cpu,
  Layers3,
  PackageOpen,
  ServerCog,
  Sparkles,
  Workflow,
} from "lucide-react"
import type { CourseSection, RoadmapStep } from "./types"

export const COURSE_SECTIONS: CourseSection[] = [
  {
    number: "01",
    title: "前言",
    href: "/courses/01-introduction/01",
    lessons: 6,
    status: "已更新",
    summary: "课程背景、适合人群和学习方式。",
    icon: Sparkles,
    lessonTitles: [
      "课程设计初衷",
      "时代背景分析",
      "课程内容介绍",
      "适合人群",
      "学习方式",
      "ZTeam",
    ],
  },
  {
    number: "02",
    title: "行业分析与需求推导",
    href: "/courses/02-requirement/01",
    lessons: 3,
    status: "已更新",
    summary: "梳理中后台开发中的重复工作，确定框架需要解决的问题。",
    icon: Workflow,
    lessonTitles: [
      "痛点：纯前端业务开发（体力活，无成长）",
      "目标：专注架构设计与基建，脱离体力活",
      "需求：搭建基于“领域模型架构”的开发框架",
    ],
  },
  {
    number: "03",
    title: "技术选型与架构设计",
    href: "/courses/03-technology-selection-and-architecture/01",
    lessons: 6,
    status: "已更新",
    summary: "比较现有方案，确定技术栈，设计 BFF 和前端领域模型。",
    icon: Layers3,
    lessonTitles: [
      "框架名称 - elpis",
      "业界方案调研",
      "项目架构设计",
      "技术选型（vue3 + nodejs）",
      "服务端 BFF 方案设计",
      "前端 领域模型 架构设计",
    ],
  },
  {
    number: "04",
    title: "基于 nodejs 实现服务端内核引擎",
    href: "/courses/04-nodejs-server-core-engine/01",
    lessons: 10,
    status: "已更新",
    summary: "搭建项目和 Git 工作流，编写 elpis-core 的加载器、路由与中间件。",
    icon: ServerCog,
    lessonTitles: [
      "创建项目 - git 环境搭建",
      "gitflow 协同流程操作演示",
      "项目初始化",
      "elpis-core 内核引擎设计",
      "elpis-core 引擎内核实现（1）",
      "elpis-core 引擎内核实现（2）",
      "elpis-core 引擎内核应用（1）",
      "elpis-core 引擎内核应用（2）",
      "elpis-core 引擎内核应用（3）",
      "elpis-core 内核引擎应用（4）",
    ],
  },
  {
    number: "05",
    title: "基于 webpack5 完成工程化建设",
    href: "/courses/05-webpack5-engineering/01",
    lessons: 7,
    status: "已更新",
    summary: "配置开发环境、资源处理和构建流程。",
    icon: Boxes,
    lessonTitles: [
      "webpack5 工程化设计",
      "webpack5 前端工程化搭建（1）",
      "webpack5 前端工程化搭建（2）",
      "webpack5 前端工程化搭建（3）",
      "webpack5 前端工程化搭建（4）",
      "elpis 前端基础建设（1）",
      "elpis 前端基础建设（2）",
    ],
  },
  {
    number: "06",
    title: "基于 vue3 完成领域模型架构建设",
    href: "/courses/06-vue3-domain-model-architecture/01",
    lessons: 19,
    status: "已更新",
    summary: "编写 DSL 和解析器，实现应用入口、表格与查询页面。",
    icon: Braces,
    lessonTitles: [
      "领域模型 DSL 设计",
      "领域模型 DSL 解析引擎",
      "模型应用 - API 实现",
      "模型应用 - 页面实现",
      "模板引擎 - dashboard 应用列表接口实现",
      "模板引擎 - dashboard 应用配置接口实现",
      "模板引擎 - dashboard headerView 实现",
      "模板引擎 - dashboard 主入口实现",
      "模板引擎 - dashboard 懒加载实现",
      "模板引擎 - SiderView 实现",
      "模板引擎 - IframeView 实现",
      "模板引擎 - SchemaView 实现",
      "模板引擎 - SchemaTable 实现（1）",
      "模板引擎 - SchemaTable 实现（2）",
      "模板引擎 - SchemaTable 实现（3）",
      "模板引擎 - SchemaTable 实现（4）",
      "模板引擎 - SchemaSearchBar 实现（1）",
      "模板引擎 - SchemaSearchBar 实现（2）",
      "领域模型 DSL 设计与实践 - 阶段性复盘总结",
    ],
  },
  {
    number: "07",
    title: "基于 vue3 完成动态组件库建设",
    href: "/courses/07-vue3-dynamic-component-library/01",
    lessons: 6,
    status: "已更新",
    summary: "实现动态表单，以及新增、编辑和详情组件。",
    icon: Cpu,
    lessonTitles: [
      "动态组件 - DSL设计",
      "动态组件 - 机制实现",
      "动态组件 - SchemaForm",
      "动态组件 - CreateForm",
      "动态组件 - EditForm",
      "动态组件 - DetailPanel",
    ],
  },
  {
    number: "08",
    title: "完成框架 npm 包抽象封装并发布",
    href: "/courses/08-framework-npm-package-and-release/01",
    lessons: 5,
    status: "已更新",
    summary: "拆分框架代码，配置打包并发布到 npm。",
    icon: PackageOpen,
    lessonTitles: [
      "抽离并发布 npm 包（1）",
      "抽离并发布 npm 包（2）",
      "抽离并发布 npm 包（3）",
      "抽离并发布 npm 包（4）",
      "抽离并发布 npm 包（5）",
    ],
  },
  {
    number: "09",
    title: "【赠课扩展】 框架应用与项目实践",
    href: "/courses/09-bonus-framework-application-and-practice/01",
    lessons: 5,
    status: "已更新",
    summary: "配置 CI/CD，编写登录、鉴权和人员管理功能。",
    icon: BookOpen,
    lessonTitles: [
      "持续集成（CI）",
      "持续部署（CD）",
      "登录功能",
      "登录校验及登出功能",
      "人员管理模块",
    ],
  },
]

export const ROADMAP_STEPS: RoadmapStep[] = [
  { title: "前言与需求", range: "01–02", href: "#chapter-01" },
  { title: "技术选型", range: "03", href: "#chapter-03" },
  { title: "服务端与构建", range: "04–05", href: "#chapter-04" },
  { title: "页面与组件", range: "06–07", href: "#chapter-06" },
  { title: "发布与实践", range: "08–09", href: "#chapter-08" },
]
